# Generated by Django 3.2.8 on 2022-02-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Testing7',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'testing7',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Testing8',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('created_on', models.DateTimeField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'testing8',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Testing9',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'testing9',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokenBlacklistBlacklistedtoken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('blacklisted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'token_blacklist_blacklistedtoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokenBlacklistOutstandingtoken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('jti', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'token_blacklist_outstandingtoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UseradministrationAlllogin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login_date', models.DateField(blank=True, null=True)),
                ('login_time', models.TimeField()),
            ],
            options={
                'db_table': 'UserAdministration_alllogin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UseradministrationAlllogout',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('logout_date', models.DateField(blank=True, null=True)),
                ('logout_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'UserAdministration_alllogout',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UseradministrationSci1Stkey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('projectid', models.CharField(blank=True, db_column='projectId', max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('jurisdiction_doctype', models.CharField(blank=True, max_length=100, null=True)),
                ('propertystate', models.CharField(blank=True, max_length=100, null=True)),
                ('dateaddded_to_kwf', models.CharField(blank=True, max_length=100, null=True)),
                ('datereceived', models.CharField(blank=True, max_length=100, null=True)),
                ('dateimaged', models.CharField(blank=True, max_length=100, null=True)),
                ('default', models.CharField(blank=True, max_length=50, null=True)),
                ('neverkeyed', models.CharField(blank=True, max_length=100, null=True)),
                ('erecordable', models.CharField(blank=True, max_length=100, null=True)),
                ('keying_duedate', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_datedue', models.CharField(blank=True, max_length=100, null=True)),
                ('isthis_a_rush', models.CharField(blank=True, max_length=100, null=True)),
                ('workflow', models.CharField(blank=True, max_length=100, null=True)),
                ('allocated_date', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('agent', models.CharField(blank=True, max_length=100, null=True)),
                ('tl_name', models.CharField(blank=True, max_length=100, null=True)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('process_status', models.CharField(max_length=15)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('stop_time_ticket', models.DateTimeField(blank=True, null=True)),
                ('start_time_ticket', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'UserAdministration_sci1stkey',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UseradministrationTeams',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('teamname', models.CharField(max_length=100, unique=True)),
                ('team_description', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'UserAdministration_teams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UseradministrationUserprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('date_joined', models.DateTimeField()),
                ('is_verified', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('is_admin', models.BooleanField(blank=True, null=True)),
                ('is_manager', models.BooleanField(blank=True, null=True)),
                ('is_tl', models.BooleanField(blank=True, null=True)),
                ('is_agent', models.BooleanField(blank=True, null=True)),
                ('orginization', models.CharField(blank=True, max_length=200, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=8)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'UserAdministration_userprofile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UseradministrationUserprofileGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'UserAdministration_userprofile_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UseradministrationUserprofileUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'UserAdministration_userprofile_user_permissions',
                'managed': False,
            },
        ),
    ]
