# Generated by Django 3.2.7 on 2021-12-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdministration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sci1stkey',
            name='agent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sci1stkey',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sci1stkey',
            name='projectId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sci1stkey',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sci1stkey',
            name='status',
            field=models.CharField(default='newtickets', max_length=15),
        ),
        migrations.AlterField(
            model_name='sci1stkey',
            name='team_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
