# Generated by Django 3.2.8 on 2022-01-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdministration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alllogout',
            name='alllogin',
        ),
    ]
