# Generated by Django 3.2.8 on 2022-02-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdministration', '0002_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('TL', 'TL'), ('Admin', 'Admin'), ('Agent', 'Agent'), ('SuperAdmin', 'SuperAdmin')], default=False, max_length=100, null=True),
        ),
    ]
