# Generated by Django 3.2.7 on 2021-12-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdministration', '0002_auto_20211215_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sci1stkey',
            name='status',
            field=models.CharField(blank=True, default='newtickets', max_length=15, null=True),
        ),
    ]
