# Generated by Django 3.2.7 on 2022-02-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdministration', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='sci1stkey',
            name='assign_tickets_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sci1stkey',
            name='assign_tickets_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sci1stkey',
            name='new_tickets_status',
            field=models.CharField(blank=True, default='newtickets', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sci1stkey',
            name='pending_tickets_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sci1stkey',
            name='pending_tickets_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
